- name: Configure SSH Key
  run: |
    mkdir -p ~/.ssh
    chmod 700 ~/.ssh
    echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
    chmod 600 ~/.ssh/id_rsa
    echo "SSH Key saved. Listing ~/.ssh contents for verification:"
    ls -la ~/.ssh
    echo "Testing private key fingerprint:"
    ssh-keygen -lf ~/.ssh/id_rsa
